spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/socialmedia
  application:
    name: socialmedia
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          client-oidc:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8182/login/oauth2/code/{registrationId}"
            scope: openid, read
        provider:
          spring:
            issuer-uri: http://localhost:9000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.oauth2: DEBUG



server:
  port: 8182
